services:
  - type: web
    name: fortune-teller-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --log-level info
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: fortune-teller-db
          property: connectionString
      - key: FLASK_APP
        value: app.py
    # Add health check
    healthCheckPath: /
    # Add automatic deploys
    autoDeploy: true

databases:
  - name: fortune-teller-db
    plan: free
    # Important: use PostgreSQL 14 or higher
    ipAllowList: []  # only allow internal connections

# Specify the scripts to run after deployment
envVarsGroups:
  - name: fortune-teller-app-env
    envVars:
      - key: FLASK_APP
        value: app.py 